// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7dtSlnWujIAc7KbhyY6RVGFt8pypEWOM',
    appId: '1:283714687956:web:735c04276144a190043c41',
    messagingSenderId: '283714687956',
    projectId: 'daoapp-c0527',
    authDomain: 'daoapp-c0527.firebaseapp.com',
    storageBucket: 'daoapp-c0527.firebasestorage.app',
    measurementId: 'G-KNEHCT8D19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH5WrErbEZ70QbjJF--laMp9MLFYWU1b4',
    appId: '1:283714687956:android:33fbfa9151b9d9c2043c41',
    messagingSenderId: '283714687956',
    projectId: 'daoapp-c0527',
    storageBucket: 'daoapp-c0527.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNzfyJyvrzXfbUcFVd4u38LoC7YVPvKeU',
    appId: '1:283714687956:ios:01b406840adb05f7043c41',
    messagingSenderId: '283714687956',
    projectId: 'daoapp-c0527',
    storageBucket: 'daoapp-c0527.firebasestorage.app',
    iosBundleId: 'com.example.daoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNzfyJyvrzXfbUcFVd4u38LoC7YVPvKeU',
    appId: '1:283714687956:ios:01b406840adb05f7043c41',
    messagingSenderId: '283714687956',
    projectId: 'daoapp-c0527',
    storageBucket: 'daoapp-c0527.firebasestorage.app',
    iosBundleId: 'com.example.daoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7dtSlnWujIAc7KbhyY6RVGFt8pypEWOM',
    appId: '1:283714687956:web:910505a13e3fcc3b043c41',
    messagingSenderId: '283714687956',
    projectId: 'daoapp-c0527',
    authDomain: 'daoapp-c0527.firebaseapp.com',
    storageBucket: 'daoapp-c0527.firebasestorage.app',
    measurementId: 'G-552CKWY6XH',
  );
}
