import 'package:daoapp/core/utils/dao_training_rating_utils.dart' as rating_utils;
import 'package:daoapp/data/models/training_drill_model.dart';

// ---------------------------------------------------------------------------
// 1. Beginner (비기너)
// ---------------------------------------------------------------------------
const TrainingDrillDefinition beginnerQuadrantBasic = TrainingDrillDefinition(
  id: 'beginner_quadrant_basic',
  titleKo: '4분할 감각 만들기',
  titleEn: 'Quadrant Basic',
  titleJa: '4分割の感覚作り',
  titleZh: '镖盘四分法入门',
  titleZhHans: '镖盘四分法入门',
  titleZhHant: '鏢盤四分法入門',
  shortDescriptionKo: '보드를 4구역으로 나눠 방향·거리 감각을 만드는 입문 드릴',
  shortDescriptionEn: 'Build basic feel using 4 board quadrants.',
  shortDescriptionJa: 'ボードを4つのエリアに分け、方向と距離感を養う入門ドリル',
  shortDescriptionZh: '将镖盘分为四个区域练习方向感。',
  shortDescriptionZhHans: '将镖盘分为四个区域练习方向感。',
  shortDescriptionZhHant: '將鏢盤分為四個區域練習方向感。',
  category: TrainingDrillCategory.boardMapping,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.beginner, maxTier: rating_utils.DaoTrainingTier.beginner),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 15,
  recommendedDarts: 60,
  targetLabel: '우상단 / 우하단 / 좌하단 / 좌상단',
  guideKo: '보드를 4구역으로 나누고 지시하는 구역에 던지세요. 1구역당 15발씩 진행합니다.',
  difficulty: DrillDifficulty.veryEasy,
  uiPattern: DrillUIPattern.boardArea,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'mode': 'quadrant', 'rounds': 20, 'dartsPerRound': 3},
);

const TrainingDrillDefinition beginnerTopBottomBasic = TrainingDrillDefinition(
  id: 'beginner_top_bottom_basic',
  titleKo: '상단/하단 영역 익히기',
  titleEn: 'Top / Bottom Area Control',
  titleJa: '上下エリアの習得',
  titleZh: '上下半区练习',
  titleZhHans: '上下半区练习',
  titleZhHant: '上下半區練習',
  shortDescriptionKo: '상단/하단 큰 영역을 목표로 던져보며 방향 감각을 만든다.',
  shortDescriptionEn: 'Learn to control top and bottom halves of the board.',
  shortDescriptionJa: '上下の大きなエリアを狙い、方向感覚を身につけます。',
  shortDescriptionZh: '练习控制镖盘的上下半部分。',
  shortDescriptionZhHans: '练习控制镖盘的上下半部分。',
  shortDescriptionZhHant: '練習控制鏢盤的上下半部分。',
  category: TrainingDrillCategory.boardMapping,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.beginner, maxTier: rating_utils.DaoTrainingTier.beginner),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 15,
  recommendedDarts: 60,
  targetLabel: '상단 / 하단',
  guideKo: '보드를 상/하로 나누어 각 영역에 30발씩 던지며 감각을 익힙니다.',
  difficulty: DrillDifficulty.veryEasy,
  uiPattern: DrillUIPattern.boardArea,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'mode': 'top_bottom', 'totalDartsPerArea': 30, 'rounds': 20},
);

const TrainingDrillDefinition beginnerAroundTheBoardSingle = TrainingDrillDefinition(
  id: 'beginner_around_board_single',
  titleKo: '싱글 한 바퀴',
  titleEn: 'Around the Board Single',
  titleJa: 'シングル一周',
  titleZh: '单倍区环盘练习',
  titleZhHans: '单倍区环盘练习',
  titleZhHant: '單倍區環盤練習',
  shortDescriptionKo: '1→20→SB까지 싱글을 한 바퀴 도는 기초 드릴',
  shortDescriptionEn: 'Hit singles 1→20 then SB in order.',
  shortDescriptionJa: '1から20、그리고SB까지 シングル一周',
  shortDescriptionZh: '按顺序击打单倍区1-20及红心。',
  shortDescriptionZhHans: '按顺序击打单倍区1-20及红心。',
  shortDescriptionZhHant: '按順序擊打單倍區1-20及紅心。',
  category: TrainingDrillCategory.boardMapping,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.beginner, maxTier: rating_utils.DaoTrainingTier.beginner),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 15,
  recommendedDarts: 60,
  targetLabel: '1~20 + SB',
  guideKo: '1부터 SB까지 순서대로 명중시키며 완주에 필요한 다트 수를 줄여보세요.',
  difficulty: DrillDifficulty.easy,
  uiPattern: DrillUIPattern.boardArea,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'mode': 'around_board', 'sequence': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', 'SB']},
);

const TrainingDrillDefinition beginnerLargeSingle20 = TrainingDrillDefinition(
  id: 'beginner_large_single_20',
  titleKo: 'Large Single 20 입문',
  titleEn: 'Large Single 20 Intro',
  titleJa: 'Large Single 20 入門',
  titleZh: '大单倍20入门',
  titleZhHans: '大单倍20入门',
  titleZhHant: '大單倍20入門',
  shortDescriptionKo: 'S20 큰 영역에 안정적으로 맞추는 감각을 만드는 입문 스코어링 드릴',
  shortDescriptionEn: 'Focus on the large S20 to build basic control.',
  shortDescriptionJa: 'S20の広いエリアに安定して入れる感覚を養うドリル',
  shortDescriptionZh: '练习大单倍20区。',
  shortDescriptionZhHans: '练习大单倍20区。',
  shortDescriptionZhHant: '練習大單倍20區。',
  category: TrainingDrillCategory.scoring,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.beginner, maxTier: rating_utils.DaoTrainingTier.beginner),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 15,
  recommendedDarts: 60,
  targetLabel: 'S20',
  guideKo: 'S20 영역만 60발을 던지며 정확도를 50% 이상으로 올리는 것을 목표로 합니다.',
  difficulty: DrillDifficulty.easy,
  uiPattern: DrillUIPattern.segmentTarget,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'targetSegment': 'S20', 'rounds': 20},
);

const TrainingDrillDefinition beginnerBigBull = TrainingDrillDefinition(
  id: 'beginner_big_bull',
  titleKo: '빅 Bull 감각',
  titleEn: 'Big Bull Feel',
  titleJa: 'ビッグブル感覚',
  titleZh: '大红心练习',
  titleZhHans: '大红心练习',
  titleZhHant: '大紅心練習',
  shortDescriptionKo: 'Bull 링 전체를 노리며 “그루핑” 감각을 만드는 드릴',
  shortDescriptionEn: 'Aim at the whole Bull ring to feel the center.',
  shortDescriptionJa: 'ブル全体を狙い、グルーピングの感覚を作るドリル',
  shortDescriptionZh: '瞄准整个红心区域。',
  shortDescriptionZhHans: '瞄准整个红心区域。',
  shortDescriptionZhHant: '瞄準整個紅心區域。',
  category: TrainingDrillCategory.bull,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.beginner, maxTier: rating_utils.DaoTrainingTier.beginner),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 15,
  recommendedDarts: 60,
  targetLabel: '전체 Bull',
  guideKo: '싱글불과 더블불을 구분하지 않고 전체 Bull 영역에 모아 던지는 연습을 합니다.',
  difficulty: DrillDifficulty.easy,
  uiPattern: DrillUIPattern.segmentTarget,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'mode': 'bull_split', 'targetArea': 'bull_split', 'totalDarts': 60, 'targetSbPlusDb': 10},
);

const TrainingDrillDefinition beginnerLooseCountUp = TrainingDrillDefinition(
  id: 'beginner_loose_countup_8r',
  titleKo: '느슨한 Count-Up',
  titleEn: 'Loose Count-Up',
  titleJa: 'ゆるいカウントアップ',
  titleZh: '轻量级高분赛',
  titleZhHans: '轻量级高分赛',
  titleZhHant: '輕量級高分賽',
  shortDescriptionKo: '점수보다는 “보드에 꽂히는 경험”을 쌓는 가벼운 8R Count-Up',
  shortDescriptionEn: 'A relaxed 8-round Count-Up to gain throwing experience.',
  shortDescriptionJa: 'スコアよりも「ボードに刺さる体験」を積むための8R',
  shortDescriptionZh: '通过高分赛增加投掷经验。',
  shortDescriptionZhHans: '通过高分赛增加投掷经验。',
  shortDescriptionZhHant: '通過高分賽增加投擲經驗。',
  category: TrainingDrillCategory.scoring,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.beginner, maxTier: rating_utils.DaoTrainingTier.beginner),
  inputMode: TrainingDrillInputMode.scoreOnly,
  estimatedMinutes: 5,
  recommendedDarts: 24,
  targetLabel: '8R Count-Up',
  guideKo: '편안하게 8라운드를 완주하며 다트가 보드에 들어가는 손맛에 집중하세요.',
  difficulty: DrillDifficulty.veryEasy,
  uiPattern: DrillUIPattern.scoreGame,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'gameType': 'countup', 'rounds': 8, 'targetScores': [200, 250, 300]},
);

// ---------------------------------------------------------------------------
// 2. Learner (러너)
// ---------------------------------------------------------------------------
const TrainingDrillDefinition learnerStandardCountUp8r = TrainingDrillDefinition(
  id: 'learner_countup_8r_standard',
  titleKo: '러너 기준 Count-Up 8R',
  titleEn: 'Learner Standard Count-Up 8R',
  titleJa: 'ラーナー基準 Count-Up 8R',
  titleZh: '标准高分赛 8R',
  titleZhHans: '标准高分赛 8R',
  titleZhHant: '標準高分賽 8R',
  shortDescriptionKo: '8R Count-Up에서 350~500점 구간을 목표로 하는 러너용 드릴',
  shortDescriptionEn: '8-round Count-Up targeting 350–500 points.',
  shortDescriptionJa: '8R Count-Upで350〜500点を目指すドリル',
  shortDescriptionZh: '目标分数为350-500的高分赛练习。',
  shortDescriptionZhHans: '目标分数为350-500的高分赛练习。',
  shortDescriptionZhHant: '目標分數為350-500的高分賽練習。',
  category: TrainingDrillCategory.scoring,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.learner, maxTier: rating_utils.DaoTrainingTier.learner),
  inputMode: TrainingDrillInputMode.scoreOnly,
  estimatedMinutes: 8,
  recommendedDarts: 24,
  targetLabel: '8R Count-Up',
  guideKo: '350점 → 400점 → 450점 → 500점 순으로 단계 목표를 정해 연습하세요.',
  difficulty: DrillDifficulty.normal,
  uiPattern: DrillUIPattern.scoreGame,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'gameType': 'countup', 'rounds': 8, 'targetScores': [350, 400, 450, 500]},
);

const TrainingDrillDefinition learnerSingle20x60 = TrainingDrillDefinition(
  id: 'learner_single20_60',
  titleKo: 'Single 20 60발',
  titleEn: 'Single 20 x 60',
  titleJa: 'シングル20 60投',
  titleZh: '单倍20 60镖',
  titleZhHans: '单倍20 60镖',
  titleZhHant: '單倍20 60鏢',
  shortDescriptionKo: '정규 거리에서 S20만 60발 던지며 명중률을 끌어올리는 드릴',
  shortDescriptionEn: 'Throw 60 darts at S20 from standard distance.',
  shortDescriptionJa: '正規の距離からS20に60投投げるドリル',
  shortDescriptionZh: '在标准距离投掷60镖单倍20。',
  shortDescriptionZhHans: '在标准距离投掷60镖单倍20练习。',
  shortDescriptionZhHant: '在標準距離投擲60鏢單倍20練習。',
  category: TrainingDrillCategory.scoring,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.learner, maxTier: rating_utils.DaoTrainingTier.learner),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 15,
  recommendedDarts: 60,
  targetLabel: 'S20',
  guideKo: '60발 중 40발 이상 명중시키는 것을 목표로 합니다.',
  difficulty: DrillDifficulty.normal,
  uiPattern: DrillUIPattern.segmentTarget,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'targetSegment': 'S20', 'totalDarts': 60, 'targetHits': 40},
);

const TrainingDrillDefinition learnerTopBottomAdvanced = TrainingDrillDefinition(
  id: 'learner_top_bottom_adv',
  titleKo: '상단/하단 영역 심화',
  titleEn: 'Top/Bottom Advanced',
  titleJa: '上下エリア深層',
  titleZh: '上下半区进阶',
  titleZhHans: '上下半区进阶练习',
  titleZhHant: '上下半區進階練習',
  shortDescriptionKo: '상단과 하단을 번갈아 공략하며 수직 방향 제어력을 높입니다.',
  shortDescriptionEn: 'Improve vertical control by switching top and bottom.',
  shortDescriptionJa: '上下を交互に狙い、垂直方向の制御力を高めます。',
  shortDescriptionZh: '通过交替上下半区练习控制。',
  shortDescriptionZhHans: '交替击打上下半区，提高垂直控制力。',
  shortDescriptionZhHant: '交替擊打上下半區，提高垂直控制力。',
  category: TrainingDrillCategory.boardMapping,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.learner, maxTier: rating_utils.DaoTrainingTier.learner),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 15,
  recommendedDarts: 60,
  targetLabel: '상단 ↔ 하단 스위치',
  guideKo: '상단 영역과 하단 영역을 3발씩 번갈아 가며 던집니다.',
  difficulty: DrillDifficulty.normal,
  uiPattern: DrillUIPattern.boardArea,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'mode': 'top_bottom', 'rounds': 20, 'switchMode': true},
);

const TrainingDrillDefinition learner20to19Switch = TrainingDrillDefinition(
  id: 'learner_20_19_switch',
  titleKo: '상단 3섹터 루프 (20/19/18)',
  titleEn: 'Top 3 Sectors Loop',
  titleJa: '上部3セクターループ',
  titleZh: '顶部三区循环',
  titleZhHans: '顶部三区循环',
  titleZhHant: '頂部三區循環',
  shortDescriptionKo: '20/19/18 상단 구역을 돌면서 빅미스를 줄이는 연습',
  shortDescriptionEn: 'Loop 20/19/18 to reduce big misses.',
  shortDescriptionJa: '20/19/18エリアを回り、ミスを減らす練習',
  shortDescriptionZh: '循环练习20/19/18。',
  shortDescriptionZhHans: '循环击打20/19/18区。',
  shortDescriptionZhHant: '循環擊打20/19/18區。',
  category: TrainingDrillCategory.scoring,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.learner, maxTier: rating_utils.DaoTrainingTier.learner),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 15,
  recommendedDarts: 60,
  targetLabel: '20 / 19 / 18',
  guideKo: '20, 19, 18번을 순차적으로 공략하며 리듬을 익힙니다.',
  difficulty: DrillDifficulty.normal,
  uiPattern: DrillUIPattern.segmentTarget,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'segments': ['20', '19', '18'], 'totalDarts': 60},
);

const TrainingDrillDefinition learner17to15Line = TrainingDrillDefinition(
  id: 'learner_17_15_line',
  titleKo: '하단 섹터 루프 (17/16/15)',
  titleEn: 'Bottom 3 Sectors Loop',
  titleJa: '下部3セクターループ',
  titleZh: '底部三区循环',
  titleZhHans: '底部三区循环',
  titleZhHant: '底部三區循環',
  shortDescriptionKo: '17/16/15 하단 구역을 공략하며 보드 아래쪽 감각을 강화합니다.',
  shortDescriptionEn: 'Strengthen bottom feel by targeting 17/16/15.',
  shortDescriptionJa: '17/16/15エリアを狙い、感覚を強化します。',
  shortDescriptionZh: '练习击打17/16/15区。',
  shortDescriptionZhHans: '练习击打底部17/16/15区。',
  shortDescriptionZhHant: '練習擊打底部17/16/15區。',
  category: TrainingDrillCategory.scoring,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.learner, maxTier: rating_utils.DaoTrainingTier.learner),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 15,
  recommendedDarts: 60,
  targetLabel: '17 / 16 / 15',
  guideKo: '17, 16, 15번을 순서대로 던지며 정확도를 체크합니다.',
  difficulty: DrillDifficulty.normal,
  uiPattern: DrillUIPattern.segmentTarget,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'segments': ['17', '16', '15'], 'totalDarts': 60},
);

// ---------------------------------------------------------------------------
// 3. Competitor (컴페티터)
// ---------------------------------------------------------------------------
const TrainingDrillDefinition compTriple201918 = TrainingDrillDefinition(
  id: 'comp_triple_20_19_18_line',
  titleKo: '트리플 루프 (T20/T19/T18)',
  titleEn: 'Top Triple Loop',
  titleJa: 'トリプルループ',
  titleZh: '高倍区循环',
  titleZhHans: '高倍区循环',
  titleZhHant: '高倍區循環',
  shortDescriptionKo: 'T20 → T19 → T18 트리플 영역을 순환하며 리듬을 만드는 연습',
  shortDescriptionEn: 'Loop triples T20–T18 to stabilize scoring.',
  shortDescriptionJa: 'T20→T19→T18を循環し、リズムを作る練習',
  shortDescriptionZh: '练习T20-T19-T18转换。',
  shortDescriptionZhHans: '循环练习T20-T19-T18转换。',
  shortDescriptionZhHant: '循環練習T20-T19-T18轉換。',
  category: TrainingDrillCategory.scoring,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.competitor, maxTier: rating_utils.DaoTrainingTier.competitor),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 12,
  recommendedDarts: 60,
  targetLabel: 'T20 / T19 / T18',
  guideKo: '트리플 3곳을 번갈아 공략하며 집중력을 유지하세요.',
  difficulty: DrillDifficulty.normal,
  uiPattern: DrillUIPattern.segmentTarget,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'segments': ['T20', 'T19', 'T18'], 'totalDarts': 60, 'loopSize': 3},
);

const TrainingDrillDefinition compDoubleClockHalf = TrainingDrillDefinition(
  id: 'comp_double_clock_half',
  titleKo: '더블 클락 (앞 절반 1-10)',
  titleEn: 'Double Clock 1-10',
  titleJa: 'ダブルクロック(前半)',
  titleZh: '双倍环盘(前10)',
  titleZhHans: '双倍环盘(前10)',
  titleZhHant: '雙倍環盤(前10)',
  shortDescriptionKo: '1부터 10까지의 더블 영역을 순차적으로 맞추는 연습입니다.',
  shortDescriptionEn: 'Hit doubles 1–10 in order.',
  shortDescriptionJa: 'D1からD10まで順に狙う練習です。',
  shortDescriptionZh: '顺序击打D1-D10。',
  shortDescriptionZhHans: '顺序击打D1到D10。',
  shortDescriptionZhHant: '順序擊打D1到D10。',
  category: TrainingDrillCategory.doublePractice,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.competitor, maxTier: rating_utils.DaoTrainingTier.competitor),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 15,
  recommendedDarts: 60,
  targetLabel: 'D1 ~ D10',
  guideKo: '체크아웃을 위해 1번부터 10번까지의 더블을 차례로 연습합니다.',
  difficulty: DrillDifficulty.normal,
  uiPattern: DrillUIPattern.boardArea,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'mode': 'double_clock', 'startFrom': 1, 'endAt': 10},
);

const TrainingDrillDefinition compDoubleClockBack = TrainingDrillDefinition(
  id: 'comp_double_clock_back',
  titleKo: '더블 클락 (뒤 절반 11-20)',
  titleEn: 'Double Clock 11-20',
  titleJa: 'ダブルクロック(後半)',
  titleZh: '双倍环盘(后10)',
  titleZhHans: '双倍环盘(后10)',
  titleZhHant: '雙倍環盤(後10)',
  shortDescriptionKo: '11부터 20까지의 더블 영역을 순차적으로 맞추는 연습입니다.',
  shortDescriptionEn: 'Hit doubles 11–20 in order.',
  shortDescriptionJa: 'D11からD20まで順に狙う練習です。',
  shortDescriptionZh: '顺序击打D11-D20。',
  shortDescriptionZhHans: '顺序击打D11到D20。',
  shortDescriptionZhHant: '順序擊打D11到D20。',
  category: TrainingDrillCategory.doublePractice,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.competitor, maxTier: rating_utils.DaoTrainingTier.competitor),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 15,
  recommendedDarts: 60,
  targetLabel: 'D11 ~ D20',
  guideKo: '나머지 더블 구역인 11번부터 20번까지 공략합니다.',
  difficulty: DrillDifficulty.normal,
  uiPattern: DrillUIPattern.boardArea,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'mode': 'double_clock', 'startFrom': 11, 'endAt': 20},
);

const TrainingDrillDefinition compCheckout40to80 = TrainingDrillDefinition(
  id: 'comp_checkout_40_80',
  titleKo: '40–80 더블 아웃 필수 구간',
  titleEn: '40–80 Double-Out Essentials',
  titleJa: '40–80 ダブルアウト必須区間',
  titleZh: '40-80 结镖练习',
  titleZhHans: '40–80 结镖练习',
  titleZhHant: '40–80 結鏢練習',
  shortDescriptionKo: '40~80 점수대를 더블로 마무리하는 필수 체크아웃 드릴',
  shortDescriptionEn: 'Practice finishing 40–80 scores via doubles.',
  shortDescriptionJa: '40~80点をダブルで上がるための必須ドリル',
  shortDescriptionZh: '练习结镖40-80。',
  shortDescriptionZhHans: '练习在40-80分区间通过双倍区结镖。',
  shortDescriptionZhHant: '練習在40-80分區間通過雙倍區結鏢。',
  category: TrainingDrillCategory.finish,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.competitor, maxTier: rating_utils.DaoTrainingTier.competitor),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 20,
  recommendedDarts: 60,
  targetLabel: '40~80 Double-Out',
  guideKo: '실전 빈도가 높은 40~80 구간을 3다트 내에 마무리하세요.',
  difficulty: DrillDifficulty.hard,
  uiPattern: DrillUIPattern.checkoutRoute,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'mode': 'checkout_practice', 'minScore': 40, 'maxScore': 80, 'maxDartsPerSet': 3, 'totalSets': 20, 'requireDoubleOut': true},
);

const TrainingDrillDefinition compCricket2019 = TrainingDrillDefinition(
  id: 'comp_cricket_20_19',
  titleKo: '크리켓 20↔19 실전 훈련',
  titleEn: 'Cricket 20↔19 Training',
  titleJa: 'クリケット 20↔19 実戦',
  titleZh: '板球20-19练习',
  titleZhHans: '板球20-19练习',
  titleZhHant: '板球20-19練習',
  shortDescriptionKo: '20과 19만 번갈아 던지며 실전 MPR 2.0+을 노리는 집중 드릴',
  shortDescriptionEn: 'Alternate 20 and 19 for real MPR training.',
  shortDescriptionJa: '20と19を交互に投げ、実戦MPRの向上を目指す',
  shortDescriptionZh: '交替击打20和19。',
  shortDescriptionZhHans: '交替击打20和19区，目标MPR 2.0+。',
  shortDescriptionZhHant: '交替擊打20和19區，目標MPR 2.0+。',
  category: TrainingDrillCategory.scoring,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.competitor, maxTier: rating_utils.DaoTrainingTier.competitor),
  inputMode: TrainingDrillInputMode.cricketMarks,
  estimatedMinutes: 10,
  recommendedDarts: 24,
  targetLabel: '20 ↔ 19',
  guideKo: '라운드별 마크 수를 입력해 실시간 MPR 2.0 이상을 노리세요.',
  difficulty: DrillDifficulty.normal,
  uiPattern: DrillUIPattern.cricketMarks,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'fixedTargets': ['20', '19', '20', '19', '20', '19', '20']},
);

const TrainingDrillDefinition compCountUpHigh20 = TrainingDrillDefinition(
  id: 'comp_countup_high_20',
  titleKo: '고득점 20 집중 카운트업',
  titleEn: 'High Score 20 Countup',
  titleJa: '20集中カウントアップ',
  titleZh: '20区高分挑战',
  titleZhHans: '20区高分挑战',
  titleZhHant: '20區高分挑戰',
  shortDescriptionKo: '20번 섹터만 사용하여 카운트업 고득점에 도전합니다.',
  shortDescriptionEn: 'Target 20 sector for high scores.',
  shortDescriptionJa: '20番セクターのみを使用して高得点を目指します。',
  shortDescriptionZh: '仅击打20区的高分赛。',
  shortDescriptionZhHans: '仅击打20区进行高分赛。',
  shortDescriptionZhHant: '僅擊打20區進行高分賽。',
  category: TrainingDrillCategory.scoring,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.competitor, maxTier: rating_utils.DaoTrainingTier.competitor),
  inputMode: TrainingDrillInputMode.scoreOnly,
  estimatedMinutes: 8,
  recommendedDarts: 24,
  targetLabel: '20 Zone Only',
  guideKo: '오직 20번 영역을 통해 높은 점수를 획득하세요.',
  difficulty: DrillDifficulty.normal,
  uiPattern: DrillUIPattern.scoreGame,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'gameType': 'countup', 'targetArea': '20', 'rounds': 8},
);

const TrainingDrillDefinition compBullDoubleIntro = TrainingDrillDefinition(
  id: 'comp_bull_double_intro',
  titleKo: '더블 불 입문 훈련',
  titleEn: 'Double Bull Intro',
  titleJa: 'ダブルブル入門',
  titleZh: '双倍红心入门',
  titleZhHans: '双倍红心入门',
  titleZhHant: '雙倍紅心入門',
  shortDescriptionKo: '싱글 불보다는 더블 불(센터) 명중을 목표로 하는 연습입니다.',
  shortDescriptionEn: 'Focus on hitting the center Double Bull.',
  shortDescriptionJa: 'ダブルブル(中央)を狙う練習です。',
  shortDescriptionZh: '集中练习击打双倍红心。',
  shortDescriptionZhHans: '集中练习击打双倍红心（圆心）。',
  shortDescriptionZhHant: '集中練習擊打雙倍紅心（圓心）。',
  category: TrainingDrillCategory.bull,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.competitor, maxTier: rating_utils.DaoTrainingTier.competitor),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 15,
  recommendedDarts: 60,
  targetLabel: 'Center Bull (DB)',
  guideKo: '가장 좁은 영역인 더블 불을 60발 중 5발 이상 명중시키는 도전입니다.',
  difficulty: DrillDifficulty.hard,
  uiPattern: DrillUIPattern.segmentTarget,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'mode': 'bull_split', 'targetArea': 'bull_split', 'totalDarts': 60, 'targetDb': 5},
);

// ---------------------------------------------------------------------------
// 4. Challenger (챌린저)
// ---------------------------------------------------------------------------
const TrainingDrillDefinition challCheckout60to100Random = TrainingDrillDefinition(
  id: 'chall_checkout_60_100_random',
  titleKo: '60~100 랜덤 체크아웃',
  titleEn: 'Random Checkout 60–100',
  titleJa: '60~100 ランダム',
  titleZh: '60-100 随机结镖',
  titleZhHans: '随机结镖 60-100',
  titleZhHant: '隨機結鏢 60-100',
  shortDescriptionKo: '60~100 점수대를 랜덤으로 받아 더블 아웃 성공률을 높입니다.',
  shortDescriptionEn: 'Random double-out finishes 60–100.',
  shortDescriptionJa: '60~100点のランダムな上がりを練習する',
  shortDescriptionZh: '随机练习60-100结镖。',
  shortDescriptionZhHans: '随机练习60-100结镖。',
  shortDescriptionZhHant: '隨機練習60-100結鏢。',
  category: TrainingDrillCategory.finish,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.challenger, maxTier: rating_utils.DaoTrainingTier.challenger),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 25,
  recommendedDarts: 180,
  targetLabel: '60~100 Double-Out',
  guideKo: '60~100 랜덤 점수를 6다트 안에 마무리하세요.',
  difficulty: DrillDifficulty.hard,
  uiPattern: DrillUIPattern.checkoutRoute,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'mode': 'checkout_practice', 'minScore': 60, 'maxScore': 100, 'maxDartsPerSet': 6, 'totalSets': 30, 'requireDoubleOut': true},
);

const TrainingDrillDefinition challDoubleClockFull = TrainingDrillDefinition(
  id: 'chall_double_clock_full',
  titleKo: '전체 더블 클락 완주',
  titleEn: 'Full Double Clock',
  titleJa: 'ダブルクロック全周',
  titleZh: '全盘双倍环绕',
  titleZhHans: '全盘双倍环绕',
  titleZhHant: '全盤雙倍環繞',
  shortDescriptionKo: 'D1부터 D20, 그리고 Bull까지 모든 더블 영역을 순환합니다.',
  shortDescriptionEn: 'Loop through all doubles and Bull.',
  shortDescriptionJa: '全てのダブルとブルを回ります。',
  shortDescriptionZh: '循环击打所有双倍和红心。',
  shortDescriptionZhHans: '全盘双倍环绕练习。',
  shortDescriptionZhHant: '全盤雙倍環繞練習。',
  category: TrainingDrillCategory.doublePractice,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.challenger, maxTier: rating_utils.DaoTrainingTier.challenger),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 20,
  recommendedDarts: 90,
  targetLabel: 'D1 ~ DBull',
  guideKo: '보드의 모든 더블 구역을 순서대로 명중시키세요.',
  difficulty: DrillDifficulty.hard,
  uiPattern: DrillUIPattern.boardArea,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'mode': 'double_clock', 'startFrom': 1, 'endAt': 20, 'includeBull': true},
);

const TrainingDrillDefinition challT20Focus60 = TrainingDrillDefinition(
  id: 'chall_t20_focus_60',
  titleKo: 'T20 집중 60발',
  titleEn: 'T20 Focus 60 Darts',
  titleJa: 'T20 集中 60投',
  titleZh: 'T20 60镖集中练习',
  titleZhHans: 'T20 60镖集中练习',
  titleZhHant: 'T20 60鏢集中練習',
  shortDescriptionKo: 'T20 60발에서 15개(25%) 이상을 노리는 고강도 훈련',
  shortDescriptionEn: 'Aim for 25%+ hit rate at T20.',
  shortDescriptionJa: 'T20に60投投げ、25%以上を目指します。',
  shortDescriptionZh: '瞄准25%以上的命中率。',
  shortDescriptionZhHans: '瞄准25%以上的命中率。',
  shortDescriptionZhHant: '瞄準25%以上的命中率。',
  category: TrainingDrillCategory.scoring,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.challenger, maxTier: rating_utils.DaoTrainingTier.challenger),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 12,
  recommendedDarts: 60,
  targetLabel: 'T20',
  guideKo: '60발 중 15개 이상 명중을 목표로 합니다.',
  difficulty: DrillDifficulty.hard,
  uiPattern: DrillUIPattern.segmentTarget,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'segments': ['T20'], 'totalDarts': 60, 'targetHits': 15},
);

const TrainingDrillDefinition challCricketFull = TrainingDrillDefinition(
  id: 'chall_cricket_full',
  titleKo: '전체 크리켓 마크 훈련',
  titleEn: 'Full Cricket Mark Training',
  titleJa: 'クリケット全ターゲット',
  titleZh: '全区板球练习',
  titleZhHans: '全区板球练习',
  titleZhHant: '全區板球練習',
  shortDescriptionKo: '크리켓의 모든 타겟(20~15, Bull)을 고르게 연습합니다.',
  shortDescriptionEn: 'Practice all cricket targets (20-15 & Bull).',
  shortDescriptionJa: 'クリケット全ターゲットを練習。',
  shortDescriptionZh: '练习所有板球区域。',
  shortDescriptionZhHans: '练习所有板球区域。',
  shortDescriptionZhHant: '練習所有板球區域。',
  category: TrainingDrillCategory.scoring,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.challenger, maxTier: rating_utils.DaoTrainingTier.challenger),
  inputMode: TrainingDrillInputMode.cricketMarks,
  estimatedMinutes: 15,
  recommendedDarts: 45,
  targetLabel: '20-15 & Bull',
  guideKo: '크리켓 핵심 영역을 순서대로 공략하며 MPR을 높이세요.',
  difficulty: DrillDifficulty.hard,
  uiPattern: DrillUIPattern.cricketMarks,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'fixedTargets': ['20', '19', '18', '17', '16', '15', 'Bull']},
);

const TrainingDrillDefinition challCountup700 = TrainingDrillDefinition(
  id: 'chall_countup_700',
  titleKo: '카운트업 700점 챌린지',
  titleEn: 'Countup 700 Challenge',
  titleJa: 'カウントアップ700点',
  titleZh: '700分挑战',
  titleZhHans: '高分赛700分挑战',
  titleZhHant: '高分賽700分挑戰',
  shortDescriptionKo: '8라운드 카운트업에서 700점 이상의 고득점을 목표로 합니다.',
  shortDescriptionEn: 'Aim for 700+ in Countup.',
  shortDescriptionJa: 'カウントアップで700点以上を目指します。',
  shortDescriptionZh: '目标分数为700。',
  shortDescriptionZhHans: '高分赛700分挑战。',
  shortDescriptionZhHant: '高分賽700分挑戰。',
  category: TrainingDrillCategory.scoring,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.challenger, maxTier: rating_utils.DaoTrainingTier.challenger),
  inputMode: TrainingDrillInputMode.scoreOnly,
  estimatedMinutes: 8,
  recommendedDarts: 24,
  targetLabel: 'Score 700+',
  guideKo: '최선을 다해 800점 벽을 넘어서보세요.',
  difficulty: DrillDifficulty.hard,
  uiPattern: DrillUIPattern.scoreGame,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'gameType': 'countup', 'rounds': 8, 'targetScore': 700},
);

// ---------------------------------------------------------------------------
// 5. Elite (엘리트)
// ---------------------------------------------------------------------------
const TrainingDrillDefinition eliteT20Precision60 = TrainingDrillDefinition(
  id: 'elite_t20_precision_60',
  titleKo: 'T20 정밀 컨트롤 60발',
  titleEn: 'T20 Precision 60',
  titleJa: 'T20 精密 60投',
  titleZh: 'T20 60镖精控练习',
  titleZhHans: 'T20 60镖精控练习',
  titleZhHant: 'T20 60鏢精控練習',
  shortDescriptionKo: 'T20 60발에서 20개 이상 명중을 노리는 정밀 드릴',
  shortDescriptionEn: 'Aim for 20+ hits at T20.',
  shortDescriptionJa: 'T20で20投以上の的中を狙う。',
  shortDescriptionZh: '目标20个以上命中。',
  shortDescriptionZhHans: 'T20 60镖精控练习。',
  shortDescriptionZhHant: 'T20 60鏢精控練習。',
  category: TrainingDrillCategory.scoring,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.elite, maxTier: rating_utils.DaoTrainingTier.elite),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 15,
  recommendedDarts: 60,
  targetLabel: 'T20 (Precision)',
  guideKo: 'T20 집중 명중률 33% 이상을 유지하세요.',
  difficulty: DrillDifficulty.veryHard,
  uiPattern: DrillUIPattern.segmentTarget,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'segments': ['T20'], 'totalDarts': 60, 'targetHits': 20},
);

const TrainingDrillDefinition eliteT20T19TripleSwitch = TrainingDrillDefinition(
  id: 'elite_t20_t19_switch',
  titleKo: '트리플 스위치 (T20/T19)',
  titleEn: 'Triple Switch T20/T19',
  titleJa: 'トリプル切り替え',
  titleZh: '高倍区转换 T20/T19',
  titleZhHans: '高倍区转换 T20/T19',
  titleZhHant: '高倍區轉換 T20/T19',
  shortDescriptionKo: 'T20과 T19를 번갈아 던지며 실전 전환 능력을 높입니다.',
  shortDescriptionEn: 'Alternate T20 and T19.',
  shortDescriptionJa: 'T20とT19を交互に狙います。',
  shortDescriptionZh: '交替击打T20和T19。',
  shortDescriptionZhHans: '交替击打T20和T19。',
  shortDescriptionZhHant: '交替擊打T20和T19。',
  category: TrainingDrillCategory.scoring,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.elite, maxTier: rating_utils.DaoTrainingTier.elite),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 15,
  recommendedDarts: 60,
  targetLabel: 'T20 ↔ T19',
  guideKo: '두 주요 트리플 영역을 오가며 감각을 유지하세요.',
  difficulty: DrillDifficulty.veryHard,
  uiPattern: DrillUIPattern.segmentTarget,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'segments': ['T20', 'T19'], 'loopSize': 2, 'totalDarts': 60},
);

const TrainingDrillDefinition eliteCheckout61to120 = TrainingDrillDefinition(
  id: 'elite_checkout_61_120',
  titleKo: '61~120 핵심 체크아웃',
  titleEn: 'Key Checkouts 61–120',
  titleJa: '61~120 主要',
  titleZh: '61-120 核心结镖',
  titleZhHans: '核心结镖 61-120',
  titleZhHant: '核心結鏢 61-120',
  shortDescriptionKo: '61~120 점수대에서 6다트 안에 마무리하는 훈련',
  shortDescriptionEn: 'Double-out finish 61–120.',
  shortDescriptionJa: '61~120点を6投以内で上がる。',
  shortDescriptionZh: '6镖内结镖61-120。',
  shortDescriptionZhHans: '核心结镖 61-120练习。',
  shortDescriptionZhHant: '核心結鏢 61-120練習。',
  category: TrainingDrillCategory.finish,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.elite, maxTier: rating_utils.DaoTrainingTier.elite),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 25,
  recommendedDarts: 180,
  targetLabel: '61~120 Double-Out',
  guideKo: '실제 경기 상황처럼 6다트 안에 아웃을 노리세요.',
  difficulty: DrillDifficulty.veryHard,
  uiPattern: DrillUIPattern.checkoutRoute,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'mode': 'checkout_practice', 'minScore': 61, 'maxScore': 120, 'maxDartsPerSet': 6, 'totalSets': 30, 'requireDoubleOut': true},
);

const TrainingDrillDefinition eliteDoubleClusterD16D20 = TrainingDrillDefinition(
  id: 'elite_double_cluster',
  titleKo: '핵심 더블 집중 (D16/D20)',
  titleEn: 'Double Cluster (D16/D20)',
  titleJa: '主要ダブル集中',
  titleZh: '核心双倍 D16/D20',
  titleZhHans: '核心双倍 D16/D20',
  titleZhHant: '核心雙倍 D16/D20',
  shortDescriptionKo: '가장 많이 쓰이는 D16과 D20 영역 정밀도를 높입니다.',
  shortDescriptionEn: 'Focus on D16 and D20.',
  shortDescriptionJa: '頻出するD16とD20の精度を高めます。',
  shortDescriptionZh: '练习D16和D20。',
  shortDescriptionZhHans: '核心双倍 (D16/D20)练习。',
  shortDescriptionZhHant: '核心雙倍 (D16/D20)練習。',
  category: TrainingDrillCategory.doublePractice,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.elite, maxTier: rating_utils.DaoTrainingTier.elite),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 15,
  recommendedDarts: 60,
  targetLabel: 'D16 & D20',
  guideKo: '최고의 마무리 무기인 D16/D20을 연마하세요.',
  difficulty: DrillDifficulty.veryHard,
  uiPattern: DrillUIPattern.segmentTarget,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'segments': ['D16', 'D20'], 'totalDarts': 60},
);

const TrainingDrillDefinition eliteCricketPowerMarks15r = TrainingDrillDefinition(
  id: 'elite_cricket_power_15r',
  titleKo: '엘리트 크리켓 15R 파워 마크',
  titleEn: 'Elite Cricket Power 15R',
  titleJa: 'エリートクリケット 15R',
  titleZh: '板球15R力炼',
  titleZhHans: '板球15R力炼',
  titleZhHant: '板球15R力煉',
  shortDescriptionKo: '15라운드 크리켓 연습을 통해 MPR 3.5+ 달성 목표',
  shortDescriptionEn: 'Aim for 3.5+ MPR in 15R.',
  shortDescriptionJa: '15RでMPR 3.5以上を目指す。',
  shortDescriptionZh: '目标MPR 3.5+。',
  shortDescriptionZhHans: '板球15R力炼练习。',
  shortDescriptionZhHant: '板球15R力煉練習。',
  category: TrainingDrillCategory.scoring,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.elite, maxTier: rating_utils.DaoTrainingTier.elite),
  inputMode: TrainingDrillInputMode.cricketMarks,
  estimatedMinutes: 15,
  recommendedDarts: 45,
  targetLabel: 'MPR 3.5+ Target',
  guideKo: '안정적인 3마크 이상 투구 감각을 유지하세요.',
  difficulty: DrillDifficulty.veryHard,
  uiPattern: DrillUIPattern.cricketMarks,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'fixedTargets': ['20', '19', '18', '17', '16', '15', 'Bull', '20', '19', '18', '17', '16', '15', 'Bull', 'Bull']},
);

const TrainingDrillDefinition eliteCountUp8r = TrainingDrillDefinition(
  id: 'elite_countup_8r',
  titleKo: '엘리트 8R 카운트업 (800+)',
  titleEn: 'Elite 8R Countup (800+)',
  titleJa: 'エリート 8R',
  titleZh: '精英级8R高分赛',
  titleZhHans: '精英级8R高分赛',
  titleZhHant: '精英級8R高分賽',
  shortDescriptionKo: '800점 이상의 고득점을 목표로 하는 훈련입니다.',
  shortDescriptionEn: 'Target 800+ in Countup.',
  shortDescriptionJa: '800点以上を目指す高強度訓練。',
  shortDescriptionZh: '目标分数为800。',
  shortDescriptionZhHans: '精英级8R高分赛。',
  shortDescriptionZhHant: '精英級8R高分賽。',
  category: TrainingDrillCategory.scoring,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.elite, maxTier: rating_utils.DaoTrainingTier.elite),
  inputMode: TrainingDrillInputMode.scoreOnly,
  estimatedMinutes: 8,
  recommendedDarts: 24,
  targetLabel: 'Score 800+',
  guideKo: '최정상급 스코어링을 위해 900점에도 도전해보세요.',
  difficulty: DrillDifficulty.veryHard,
  uiPattern: DrillUIPattern.scoreGame,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'gameType': 'countup', 'rounds': 8, 'targetScore': 800},
);

// ---------------------------------------------------------------------------
// 6. Pro (프로)
// ---------------------------------------------------------------------------
const TrainingDrillDefinition pro501Standard18darts = TrainingDrillDefinition(
  id: 'pro_501_standard_18darts',
  titleKo: '501 Double-Out 18다트',
  titleEn: '501 Double-Out 18 Darts',
  titleJa: '501 18投',
  titleZh: '501 18镖结镖',
  titleZhHans: '501 18镖结镖',
  titleZhHant: '501 18鏢結鏢',
  shortDescriptionKo: '18다트 이내 501 마무리가 가능한지 체크합니다.',
  shortDescriptionEn: 'Finish 501 within 18 darts.',
  shortDescriptionJa: '18投以内での501完走をチェック。',
  shortDescriptionZh: '18镖内完成501。',
  shortDescriptionZhHans: '501 18镖结镖练习。',
  shortDescriptionZhHant: '501 18鏢結鏢練習。',
  category: TrainingDrillCategory.scoring,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.pro, maxTier: rating_utils.DaoTrainingTier.pro),
  inputMode: TrainingDrillInputMode.scoreOnly,
  estimatedMinutes: 25,
  recommendedDarts: 180,
  targetLabel: '501 Double-Out',
  guideKo: '매 경기 18다트 완주를 위해 정밀하게 스코어링하세요.',
  difficulty: DrillDifficulty.veryHard,
  uiPattern: DrillUIPattern.scoreGame,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'gameType': '501_multi_18darts', 'totalSets': 10, 'successThresholdDarts': 18, 'minDartsPerLeg': 9, 'maxDartsPerLeg': 30},
);

const TrainingDrillDefinition proT20_90Darts = TrainingDrillDefinition(
  id: 'pro_t20_90darts',
  titleKo: '프로 T20 집중 90발',
  titleEn: 'Pro T20 Focus 90',
  titleJa: 'プロ T20 90投',
  titleZh: '职业级T20区90镖',
  titleZhHans: '职业级T20区90镖',
  titleZhHant: '職業級T20區90鏢',
  shortDescriptionKo: '90발 중 35% 이상 T20 명중률을 유지하는 고강도 드릴',
  shortDescriptionEn: 'Maintain 35%+ at T20 over 90 darts.',
  shortDescriptionJa: 'T20的中率35%以上を維持する。',
  shortDescriptionZh: '命中率35%以上。',
  shortDescriptionZhHans: '职业级T20区90镖练习。',
  shortDescriptionZhHant: '職業級T20區90鏢練習。',
  category: TrainingDrillCategory.scoring,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.pro, maxTier: rating_utils.DaoTrainingTier.pro),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 20,
  recommendedDarts: 90,
  targetLabel: 'T20 (Hit Rate 35%+)',
  guideKo: '최소 32개 이상의 T20을 명중시켜야 합니다.',
  difficulty: DrillDifficulty.veryHard,
  uiPattern: DrillUIPattern.segmentTarget,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'segments': ['T20'], 'totalDarts': 90, 'targetHits': 32},
);

const TrainingDrillDefinition proHighFinishSet8 = TrainingDrillDefinition(
  id: 'pro_high_finish_set_8',
  titleKo: '대표 하이 피니시 8개 세트',
  titleEn: 'High Finish Set of 8',
  titleJa: 'ハイフィニッシュ8種',
  titleZh: '8种高结镖练习',
  titleZhHans: '8种高结镖练习',
  titleZhHant: '8種高結鏢練習',
  shortDescriptionKo: '170~153 하이 피니시 루트를 숙달하는 드릴',
  shortDescriptionEn: 'Master 8 high finish routes.',
  shortDescriptionJa: '170から153のルートをマスター。',
  shortDescriptionZh: '练习8种高分结镖。',
  shortDescriptionZhHans: '8种高结镖练习。',
  shortDescriptionZhHant: '8種高結鏢練習。',
  category: TrainingDrillCategory.finish,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.pro, maxTier: rating_utils.DaoTrainingTier.pro),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 25,
  recommendedDarts: 120,
  targetLabel: 'High Finish 8 Types',
  guideKo: '최고 난이도 아웃 루트를 하나씩 정복하세요.',
  difficulty: DrillDifficulty.veryHard,
  uiPattern: DrillUIPattern.checkoutRoute,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'mode': 'checkout_practice', 'minScore': 153, 'maxScore': 170, 'totalSets': 40, 'maxDartsPerSet': 3, 'scores': [170, 167, 164, 161, 160, 158, 157, 153]},
);

const TrainingDrillDefinition proCricketHighMpr15r = TrainingDrillDefinition(
  id: 'pro_cricket_high_mpr',
  titleKo: '프로 크리켓 MPR 4.5+ 훈련',
  titleEn: 'Pro Cricket MPR 4.5+',
  titleJa: 'プロ MPR 4.5+',
  titleZh: '职业板球 MPR 4.5+',
  titleZhHans: '职业板球 MPR 4.5+',
  titleZhHant: '職業板球 MPR 4.5+',
  shortDescriptionKo: 'MPR 4.5 이상을 유지하며 최정상급 감각 유지',
  shortDescriptionEn: 'Maintain 4.5+ MPR.',
  shortDescriptionJa: 'MPR 4.5以上を維持し続ける。',
  shortDescriptionZh: '目标MPR 4.5+。',
  shortDescriptionZhHans: '职业板球 MPR 4.5+练习。',
  shortDescriptionZhHant: '職業板球 MPR 4.5+練習。',
  category: TrainingDrillCategory.scoring,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.pro, maxTier: rating_utils.DaoTrainingTier.pro),
  inputMode: TrainingDrillInputMode.cricketMarks,
  estimatedMinutes: 15,
  recommendedDarts: 45,
  targetLabel: 'MPR 4.5+ Target',
  guideKo: '거의 매 투구 트리플 명중이 필요합니다.',
  difficulty: DrillDifficulty.veryHard,
  uiPattern: DrillUIPattern.cricketMarks,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'fixedTargets': ['20', '19', '18', '17', '16', '15', 'Bull', '20', '19', '18', '17', '16', '15', 'Bull', 'Bull']},
);

const TrainingDrillDefinition proBull90 = TrainingDrillDefinition(
  id: 'pro_bull_90',
  titleKo: '프로 Bull 집중 90발',
  titleEn: 'Pro Bull 90 Darts',
  titleJa: 'プロ ブル 90',
  titleZh: '职业红心90镖',
  titleZhHans: '职业级红心 90镖',
  titleZhHant: '職業級紅心 90鏢',
  shortDescriptionKo: 'Bull 90발 중 50개 이상 명중을 노리는 훈련',
  shortDescriptionEn: 'Aim for 50+ bull hits.',
  shortDescriptionJa: '90投中50投以上のブル命中を目指す。',
  shortDescriptionZh: '目标命中50个。',
  shortDescriptionZhHans: '职业级红心 90镖。',
  shortDescriptionZhHant: '職業級紅心 90鏢。',
  category: TrainingDrillCategory.bull,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.pro, maxTier: rating_utils.DaoTrainingTier.pro),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 18,
  recommendedDarts: 90,
  targetLabel: 'Bull (50+ Hits)',
  guideKo: '센터 공략 능력을 최고 수준으로 유지하세요.',
  difficulty: DrillDifficulty.veryHard,
  uiPattern: DrillUIPattern.segmentTarget,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'mode': 'bull_split', 'targetArea': 'bull_split', 'totalDarts': 90, 'targetSbPlusDb': 50},
);

const TrainingDrillDefinition proClutchDouble2Darts30x = TrainingDrillDefinition(
  id: 'pro_clutch_double',
  titleKo: '클러치 더블 (2다트 피니시)',
  titleEn: 'Clutch Double (2-Darts)',
  titleJa: 'クラッチダブル',
  titleZh: '关键双倍结镖',
  titleZhHans: '关键双倍区 (2镖结镖)',
  titleZhHant: '關鍵雙倍區 (2鏢結鏢)',
  shortDescriptionKo: '2다트 안에 더블을 명중시키는 훈련을 30회 반복',
  shortDescriptionEn: 'Finish doubles in 2 darts x 30.',
  shortDescriptionJa: '2投以内でのダブル成功を30回。',
  shortDescriptionZh: '2镖内完成结镖30次。',
  shortDescriptionZhHans: '关键双倍区 (2镖结镖)练习。',
  shortDescriptionZhHant: '關鍵雙倍區 (2鏢結鏢)練習。',
  category: TrainingDrillCategory.doublePractice,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.pro, maxTier: rating_utils.DaoTrainingTier.pro),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 20,
  recommendedDarts: 60,
  targetLabel: 'Random Doubles',
  guideKo: '단 한 번의 기회를 놓치지 않는 연습입니다.',
  difficulty: DrillDifficulty.veryHard,
  uiPattern: DrillUIPattern.boardArea,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'mode': 'checkout_practice', 'minScore': 2, 'maxScore': 40, 'maxDartsPerSet': 2, 'totalSets': 30, 'requireDoubleOut': true},
);

const TrainingDrillDefinition proCountUp8r = TrainingDrillDefinition(
  id: 'pro_countup_8r',
  titleKo: '프로 8R 카운트업 (1000+)',
  titleEn: 'Pro 8R Countup (1000+)',
  titleJa: 'プロ 8R',
  titleZh: '职业8R高分赛',
  titleZhHans: '职业8R高分赛',
  titleZhHant: '職業8R高分賽',
  shortDescriptionKo: '1000점 이상의 고득점을 목표로 하는 훈련',
  shortDescriptionEn: 'Target 1000+ in Countup.',
  shortDescriptionJa: '1000点以上を目指す高次元の訓練。',
  shortDescriptionZh: '目标分数为1000。',
  shortDescriptionZhHans: '职业8R高分赛。',
  shortDescriptionZhHant: '職業8R高分賽。',
  category: TrainingDrillCategory.scoring,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.pro, maxTier: rating_utils.DaoTrainingTier.pro),
  inputMode: TrainingDrillInputMode.scoreOnly,
  estimatedMinutes: 8,
  recommendedDarts: 24,
  targetLabel: 'Score 1000+',
  guideKo: '단 한 번의 미스도 허용되지 않는 수준입니다.',
  difficulty: DrillDifficulty.veryHard,
  uiPattern: DrillUIPattern.scoreGame,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'gameType': 'countup', 'rounds': 8, 'targetScore': 1000},
);

// ---------------------------------------------------------------------------
// 7. Master (마스터)
// ---------------------------------------------------------------------------
const TrainingDrillDefinition masterT20_120Darts = TrainingDrillDefinition(
  id: 'master_t20_120darts',
  titleKo: '마스터 T20 무한 스코어링 (120발)',
  titleEn: 'Master T20 Scoring (120)',
  titleJa: 'マスター 120投',
  titleZh: '大师级T20 120镖',
  titleZhHans: '大师级T20区120镖',
  titleZhHant: '大師級T20區120鏢',
  shortDescriptionKo: '120발 동안 T20 명중률 40% 이상 유지',
  shortDescriptionEn: 'Maintain 40%+ at T20 over 120 darts.',
  shortDescriptionJa: 'T20的中率40%以上を完遂する。',
  shortDescriptionZh: '命中率40%以上。',
  shortDescriptionZhHans: '大师级T20区120镖练习。',
  shortDescriptionZhHant: '大師級T20區120鏢練習。',
  category: TrainingDrillCategory.scoring,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.master, maxTier: rating_utils.DaoTrainingTier.master),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 30,
  recommendedDarts: 120,
  targetLabel: 'T20 (Hit Rate 40%+)',
  guideKo: '총 48개 이상의 T20을 명중시켜야 합니다.',
  difficulty: DrillDifficulty.veryHard,
  uiPattern: DrillUIPattern.segmentTarget,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'segments': ['T20'], 'totalDarts': 120, 'targetHits': 48},
);

const TrainingDrillDefinition master170RouteFocused30 = TrainingDrillDefinition(
  id: 'master_170_route_focused_30',
  titleKo: '170 체크아웃 루트 집중',
  titleEn: '170 Checkout Route Focus',
  titleJa: '170 集中',
  titleZh: '170 结镖专注',
  titleZhHans: '170 结镖专注',
  titleZhHant: '170 結鏢專注',
  shortDescriptionKo: 'T20-T20-Bull 루트를 몸에 새기는 훈련',
  shortDescriptionEn: 'Fix T20-T20-Bull in muscle memory.',
  shortDescriptionJa: 'T20-T20-Bullを体に叩き込む。',
  shortDescriptionZh: '专注170结镖路线。',
  shortDescriptionZhHans: '170 结镖专注练习。',
  shortDescriptionZhHant: '170 結鏢專注練習。',
  category: TrainingDrillCategory.finish,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.master, maxTier: rating_utils.DaoTrainingTier.master),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 25,
  recommendedDarts: 90,
  targetLabel: '170 (T20-T20-Bull)',
  guideKo: '최고점 피니시 루트를 근육이 기억하게 하세요.',
  difficulty: DrillDifficulty.veryHard,
  uiPattern: DrillUIPattern.checkoutRoute,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'mode': 'checkout_practice', 'minScore': 170, 'maxScore': 170, 'totalSets': 30, 'maxDartsPerSet': 3, 'route': ['T20', 'T20', 'Bull']},
);

const TrainingDrillDefinition masterCricket4mpr15r = TrainingDrillDefinition(
  id: 'master_cricket_4mpr',
  titleKo: '마스터 크리켓 MPR 5.5+ 도전',
  titleEn: 'Master Cricket MPR 5.5+',
  titleJa: 'マスター MPR 5.5+',
  titleZh: '大师板球 MPR 5.5+',
  titleZhHans: '大师板球 MPR 5.5+',
  titleZhHant: '大師板球 MPR 5.5+',
  shortDescriptionKo: '15라운드 동안 MPR 5.5 이상 유지 도전',
  shortDescriptionEn: 'Maintain 5.5+ MPR.',
  shortDescriptionJa: 'MPR 5.5以上を15R維持。',
  shortDescriptionZh: '目标MPR 5.5+。',
  shortDescriptionZhHans: '大师板球 MPR 5.5+练习。',
  shortDescriptionZhHant: '大師板球 MPR 5.5+練習。',
  category: TrainingDrillCategory.scoring,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.master, maxTier: rating_utils.DaoTrainingTier.master),
  inputMode: TrainingDrillInputMode.cricketMarks,
  estimatedMinutes: 15,
  recommendedDarts: 45,
  targetLabel: 'MPR 5.5+ Target',
  guideKo: '모든 투구가 트리플 혹은 불 정중앙이어야 합니다.',
  difficulty: DrillDifficulty.veryHard,
  uiPattern: DrillUIPattern.cricketMarks,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'fixedTargets': ['20', '19', '18', '17', '16', '15', 'Bull', '20', '19', '18', '17', '16', '15', 'Bull', 'Bull']},
);

const TrainingDrillDefinition masterBullPrecision90 = TrainingDrillDefinition(
  id: 'master_bull_precision_90',
  titleKo: 'Bull 정밀 90발',
  titleEn: 'Bull Precision 90',
  titleJa: 'ブル 90',
  titleZh: '红心精密90镖',
  titleZhHans: '红心精密90镖',
  titleZhHant: '紅心精密90鏢',
  shortDescriptionKo: 'Bull 90발 중 SB+DB 60개, DB 20개 노리는 드릴',
  shortDescriptionEn: 'Aim for 60 Bulls and 20 DBs.',
  shortDescriptionJa: 'SB+DB 60、DB 20を目指す。',
  shortDescriptionZh: '目标红心60，双倍红心20。',
  shortDescriptionZhHans: '红心精密90镖练习。',
  shortDescriptionZhHant: '紅心精密90鏢練習。',
  category: TrainingDrillCategory.bull,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.master, maxTier: rating_utils.DaoTrainingTier.master),
  inputMode: TrainingDrillInputMode.hitCount,
  estimatedMinutes: 18,
  recommendedDarts: 90,
  targetLabel: 'Bull 90 Darts',
  guideKo: '최정상급 불 적중 능력을 완성하세요.',
  difficulty: DrillDifficulty.veryHard,
  uiPattern: DrillUIPattern.segmentTarget,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'mode': 'bull_split', 'targetArea': 'bull_split', 'totalDarts': 90, 'targetSbPlusDb': 60, 'targetDb': 20},
);

const TrainingDrillDefinition masterCountUp8r = TrainingDrillDefinition(
  id: 'master_countup_8r',
  titleKo: '마스터 8R 카운트업 (1100+)',
  titleEn: 'Master 8R Countup (1100+)',
  titleJa: 'マスター 8R',
  titleZh: '大师级8R高分赛',
  titleZhHans: '大师级8R高分赛',
  titleZhHant: '大師級8R高分賽',
  shortDescriptionKo: '1100점 이상의 완벽한 8라운드 지향',
  shortDescriptionEn: 'Target 1100+ in Countup.',
  shortDescriptionJa: '1100点以上を目指すマスターの領域。',
  shortDescriptionZh: '目标分数为1100。',
  shortDescriptionZhHans: '大师级8R高分赛。',
  shortDescriptionZhHant: '大師級8R高分賽。',
  category: TrainingDrillCategory.scoring,
  tierRange: DrillTierRange(minTier: rating_utils.DaoTrainingTier.master, maxTier: rating_utils.DaoTrainingTier.master),
  inputMode: TrainingDrillInputMode.scoreOnly,
  estimatedMinutes: 8,
  recommendedDarts: 24,
  targetLabel: 'Score 1100+',
  guideKo: '이 영역에서는 9다트 T20이 기본입니다.',
  difficulty: DrillDifficulty.veryHard,
  uiPattern: DrillUIPattern.scoreGame,
  runPanelType: TrainingDrillRunPanelType.genericHit,
  extraConfig: {'gameType': 'countup', 'rounds': 8, 'targetScore': 1100},
);

/// ===============================
/// 티어별 드릴 매핑
/// ===============================

final Map<rating_utils.DaoTrainingTier, List<TrainingDrillDefinition>>
kTrainingDrillsByTier = {
  rating_utils.DaoTrainingTier.beginner: [
    beginnerQuadrantBasic,
    beginnerTopBottomBasic,
    beginnerAroundTheBoardSingle,
    beginnerLargeSingle20,
    beginnerBigBull,
    beginnerLooseCountUp,
  ],
  rating_utils.DaoTrainingTier.learner: [
    learnerStandardCountUp8r,
    learnerSingle20x60,
    learnerTopBottomAdvanced,
    learner20to19Switch,
    learner17to15Line,
  ],
  rating_utils.DaoTrainingTier.competitor: [
    compTriple201918,
    compDoubleClockHalf,
    compDoubleClockBack,
    compCheckout40to80,
    compCricket2019,
    compCountUpHigh20,
    compBullDoubleIntro,
  ],
  rating_utils.DaoTrainingTier.challenger: [
    challCheckout60to100Random,
    challDoubleClockFull,
    challT20Focus60,
    challCricketFull,
    challCountup700,
  ],
  rating_utils.DaoTrainingTier.elite: [
    eliteT20Precision60,
    eliteT20T19TripleSwitch,
    eliteCheckout61to120,
    eliteDoubleClusterD16D20,
    eliteCricketPowerMarks15r,
    eliteCountUp8r,
  ],
  rating_utils.DaoTrainingTier.pro: [
    pro501Standard18darts,
    proT20_90Darts,
    proHighFinishSet8,
    proCricketHighMpr15r,
    proBull90,
    proClutchDouble2Darts30x,
    proCountUp8r,
  ],
  rating_utils.DaoTrainingTier.master: [
    masterT20_120Darts,
    master170RouteFocused30,
    masterCricket4mpr15r,
    masterBullPrecision90,
    masterCountUp8r,
  ],
};

List<TrainingDrillDefinition> getDrillsForTier(rating_utils.DaoTrainingTier tier) {
  return kTrainingDrillsByTier[tier] ?? const <TrainingDrillDefinition>[];
}

/// 🔹 [추가] 전체 드릴 리스트 반환 함수
List<TrainingDrillDefinition> getAllTrainingDrills() {
  final List<TrainingDrillDefinition> all = [];
  for (var list in kTrainingDrillsByTier.values) {
    all.addAll(list);
  }
  return all;
}